from PIL import Image
import streamlit as st
st.markdown("<h3>Outcome</h3>", unsafe_allow_html=True)
st.markdown("As the diagram below showed, the data is spliting in 70 - 30 for OUTCOME, so no action is needed. ")
st.components.v1.html(open("outcome.html", 'r').read(), height=500)
st.markdown("<h3>Pregnancies</h3>", unsafe_allow_html=True)
st.markdown("All data in this Pregnancies column is normal, so no action needed. ")
st.components.v1.html(open("pregnancies.html", 'r').read(), height=500)

st.markdown("<h3>Glucose</h3>", unsafe_allow_html=True)
st.markdown('As you can see, there is 5 "0" value which is impossible for human glucose, so the "0" need to be replace with mean. The reason mean was choosen is because the distribution of the variable is approximately normal.')
st.components.v1.html(open("glucose.html", 'r').read(), height=400)
st.markdown("After cleaning", unsafe_allow_html=True)
st.components.v1.html(open("glucoseafterclean.html", 'r').read(), height=400)
st.markdown("<h3>Blood Pressure</h3>", unsafe_allow_html=True)
st.markdown('As you can see, there is 35 "0" value which is impossible for human blood pressure, so the "0" need to be replace with mean. The reason mean was choosen is because the distribution of the variable is approximately normal.')
st.components.v1.html(open("bloodPressure.html", 'r').read(), height=400)
st.markdown("After cleaning", unsafe_allow_html=True)
st.components.v1.html(open("bloodPressureafterclean.html", 'r').read(), height=400)
st.markdown("<h3>Skin Thickness</h3>", unsafe_allow_html=True)
st.markdown('For skin thickness, the "0" need to be replace with median. The reason median was choosen is because the distribution is skewed.')
st.components.v1.html(open("skinthickness.html", 'r').read(), height=400)
st.markdown("After cleaning", unsafe_allow_html=True)
st.components.v1.html(open("skinthicknessafterclean.html", 'r').read(), height=400)
st.markdown("<h3>Insulin</h3>", unsafe_allow_html=True)
st.markdown('For insulin, the "0" need to be replace with median. The reason median was choosen is because the distribution is skewed.')
st.components.v1.html(open("insulin.html", 'r').read(), height=400)
st.markdown("After cleaning", unsafe_allow_html=True)
st.components.v1.html(open("insulinafterclean.html", 'r').read(), height=400)
st.markdown("<h3>BMI</h3>", unsafe_allow_html=True)
st.markdown('As you can see in the diagram below, there is also a lot of "0" value, so the propose method for this field is to be replace with mean. The reason mean was choosen is because the distribution of the variable is approximately normal.')
st.components.v1.html(open("bmi.html", 'r').read(), height=400)
st.markdown("After cleaning", unsafe_allow_html=True)
st.components.v1.html(open("bmiafterclean.html", 'r').read(), height=400)
st.markdown("<h3>DiabetesPedigreeFunction</h3>", unsafe_allow_html=True)
st.markdown('As you can see in the diagram below, all data is in the possible range of DiabetesPedigreeFunction, and there is no "0" value, so no action will be needed')
st.components.v1.html(open("diabetespedigreefunction.html", 'r').read(), height=400)
st.markdown("<h3>Age</h3>", unsafe_allow_html=True)
st.markdown('The data is in possible range so no action needed')
st.components.v1.html(open("age.html", 'r').read(), height=400)
